"""
Shared test infrastructure for {MODEL_NAME} component-level equivalence tests.

Auto-generated by the equivalence framework. Agent fills in model-specific
constants and adds test files.

Usage: Copy to {EXP_DIR}/tests/conftest.py, update constants, then write
test_NN_<component>.py files following the test_template.py pattern.
"""
import os
import sys

os.environ["NXD_CPU_MODE"] = "1"

# Update these paths for your model
sys.path.insert(0, "{PORT_MODULE_DIR}")  # Directory containing target modeling file
sys.path.insert(0, "{SCRIPTS_DIR}")      # Directory containing tensor_compare.py

import pytest
import torch
import numpy as np

# ── Constants (from model's config.json) ── UPDATE THESE
HIDDEN_SIZE = 0       # e.g., 1024
NUM_HEADS = 0         # e.g., 16
NUM_KV_HEADS = 0      # e.g., 8
HEAD_DIM = 0          # e.g., 128 (may differ from hidden_size // num_heads)
INTERMEDIATE_SIZE = 0 # e.g., 3072
VOCAB_SIZE = 0        # e.g., 151936
NUM_LAYERS = 0        # e.g., 28
RMS_NORM_EPS = 1e-6   # from config.json
BS = 1                # Keep small for fast tests
SEQ_LEN = 8           # Keep small for fast tests
VOCAB_SIZE_SMALL = 1024  # Reduced vocab for embedding/lm_head tests

TOLERANCE_RATIO = 1.2
MODEL_PATH = "{HF_MODEL_PATH}"

# ── Three-tensor comparison ──
from tensor_compare import compare_3tensors, check_3tensor_result

# ── CPU-mode environment management ──
from neuronx_distributed.parallel_layers import parallel_state

def _init_cpu_env_tp1():
    os.environ["NXD_CPU_MODE"] = "1"
    os.environ["WORLD_SIZE"] = "1"
    os.environ["MASTER_ADDR"] = "localhost"
    os.environ["MASTER_PORT"] = "8080"
    os.environ["RANK"] = "0"
    if parallel_state.model_parallel_is_initialized():
        parallel_state.destroy_model_parallel()
    if torch.distributed.is_initialized():
        torch.distributed.destroy_process_group()
    torch.distributed.init_process_group(backend="gloo")
    parallel_state.initialize_model_parallel(tensor_model_parallel_size=1)

def _destroy_mp():
    if parallel_state.model_parallel_is_initialized():
        parallel_state.destroy_model_parallel()
    if torch.distributed.is_initialized():
        torch.distributed.destroy_process_group()

@pytest.fixture(scope="session", autouse=True)
def init_cpu_env_session():
    _init_cpu_env_tp1()
    yield
    _destroy_mp()

@pytest.fixture(autouse=True)
def seed_every_test():
    torch.manual_seed(42)
    np.random.seed(42)
